name: bda

services:

  neo4j:
    image: neo4j:enterprise
    container_name: mygraph
    ports: 
      - "7474:7474"
      - "7688:7688"
    environment:
      NEO4J_PLUGINS: '["graph-data-science","apoc","apoc-extended"]'
      NEO4J_AUTH: "none"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_apoc_export_file_enabled: "true" 
      NEO4J_apoc_import_file_enabled: "true" 
      NEO4J_apoc_import_file_use__neo4j__config: "false"
      NEO4J_server_directories_import: "/var/lib/neo4j/files"
    volumes:
      - ./data:/var/lib/neo4j/files